.TH AMULE-EMC 1 "July 31, 2008"
.SH NAME
amule-emc \- list links inside emulecollection files
.SH SYNOPSIS
.B amule-emc
.RI [ options ] " files" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B amule-emc
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBamule-emc\fP is a program to list links inside emulecollection files.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-h
Show summary of options.
.TP
.B \-v
Show version of program.
.SH SEE ALSO
.BR ed2k (1),
.BR amule (1).
.br
.SH AUTHOR
amule-emc was written by Johannes Krampf <wuischke@amule.org>.
.PP
This manual page was written by Sandro Tosi <matrixhasu@gmail.com>,
for the Debian project (but may be used by others).
